version: '3.3'

services:
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: P@ssw0rd123!!
      MYSQL_DATABASE: wp_syarif
      MYSQL_USER: wp_syarif
      MYSQL_PASSWORD: P@ssw0rd123!!

  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    ports:
      - "8000:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST:  db:3306
      WORDPRESS_DB_USER:  wp_syarif
      WORDPRESS_DB_PASSWORD: P@ssw0rd123!!
      WORDPRESS_DB_NAME:  wp_syarif
volumes:
  db_data: {}